//! 错误码常量定义
//!
//! 前端通过 code 查找 i18n 翻译，message 字段作为开发调试信息。

// Path
pub const PATH_EMPTY: &str = "PATH_EMPTY";
pub const PATH_TRAVERSAL: &str = "PATH_TRAVERSAL";
pub const PATH_NOT_ABSOLUTE: &str = "PATH_NOT_ABSOLUTE";
pub const PATH_NOT_FOUND: &str = "PATH_NOT_FOUND";
pub const PATH_ALREADY_EXISTS: &str = "PATH_ALREADY_EXISTS";
pub const PATH_NOT_DIRECTORY: &str = "PATH_NOT_DIRECTORY";

// Workspace
pub const WORKSPACE_NOT_FOUND: &str = "WORKSPACE_NOT_FOUND";
pub const WORKSPACE_NAME_EMPTY: &str = "WORKSPACE_NAME_EMPTY";
pub const WORKSPACE_NAME_DUPLICATE: &str = "WORKSPACE_NAME_DUPLICATE";
pub const WORKSPACE_NAME_INVALID: &str = "WORKSPACE_NAME_INVALID";
pub const WORKSPACE_NAME_BLANK: &str = "WORKSPACE_NAME_BLANK";

// Project
pub const PROJECT_NOT_FOUND: &str = "PROJECT_NOT_FOUND";
pub const PROJECT_ALREADY_EXISTS: &str = "PROJECT_ALREADY_EXISTS";
pub const PROJECT_NAME_EMPTY: &str = "PROJECT_NAME_EMPTY";

// Worktree
pub const WORKTREE_NAME_EMPTY: &str = "WORKTREE_NAME_EMPTY";
pub const WORKTREE_NAME_INVALID: &str = "WORKTREE_NAME_INVALID";
pub const WORKTREE_NAME_BLANK: &str = "WORKTREE_NAME_BLANK";
pub const WORKTREE_NOT_GIT_REPO: &str = "WORKTREE_NOT_GIT_REPO";
pub const WORKTREE_LIST_FAILED: &str = "WORKTREE_LIST_FAILED";
pub const WORKTREE_CREATE_FAILED: &str = "WORKTREE_CREATE_FAILED";
pub const WORKTREE_DELETE_FAILED: &str = "WORKTREE_DELETE_FAILED";

// Git
pub const GIT_URL_EMPTY: &str = "GIT_URL_EMPTY";
pub const GIT_URL_INVALID_PROTOCOL: &str = "GIT_URL_INVALID_PROTOCOL";
pub const GIT_URL_INVALID_CHARS: &str = "GIT_URL_INVALID_CHARS";
pub const GIT_CLONE_TIMEOUT: &str = "GIT_CLONE_TIMEOUT";
pub const GIT_CLONE_FAILED: &str = "GIT_CLONE_FAILED";
pub const GIT_OPERATION_SUCCESS: &str = "GIT_OPERATION_SUCCESS";

// Command
pub const COMMAND_EMPTY: &str = "COMMAND_EMPTY";
pub const COMMAND_INVALID_CHARS: &str = "COMMAND_INVALID_CHARS";
pub const COMMAND_SUBSHELL_INJECTION: &str = "COMMAND_SUBSHELL_INJECTION";

// MCP
pub const MCP_NAME_EMPTY: &str = "MCP_NAME_EMPTY";
pub const MCP_NAME_TOO_LONG: &str = "MCP_NAME_TOO_LONG";
pub const MCP_NAME_INVALID: &str = "MCP_NAME_INVALID";

// Todo
pub const TODO_TITLE_EMPTY: &str = "TODO_TITLE_EMPTY";
pub const TODO_NOT_FOUND: &str = "TODO_NOT_FOUND";
pub const TODO_SCOPE_REF_REQUIRED: &str = "TODO_SCOPE_REF_REQUIRED";
pub const SUBTASK_TITLE_EMPTY: &str = "SUBTASK_TITLE_EMPTY";
pub const SUBTASK_NOT_FOUND: &str = "SUBTASK_NOT_FOUND";

// Spec
pub const SPEC_TITLE_EMPTY: &str = "SPEC_TITLE_EMPTY";
pub const SPEC_NOT_FOUND: &str = "SPEC_NOT_FOUND";

// Skill
pub const SKILL_NAME_EMPTY: &str = "SKILL_NAME_EMPTY";
pub const SKILL_NAME_PATH_SEPARATOR: &str = "SKILL_NAME_PATH_SEPARATOR";
pub const SKILL_NAME_DOT_PREFIX: &str = "SKILL_NAME_DOT_PREFIX";

// Settings
pub const PROXY_NOT_ENABLED: &str = "PROXY_NOT_ENABLED";
pub const MIGRATION_SYSTEM_DIR: &str = "MIGRATION_SYSTEM_DIR";
pub const MIGRATION_DIR_NOT_EMPTY: &str = "MIGRATION_DIR_NOT_EMPTY";
pub const MIGRATION_SAME_DIR: &str = "MIGRATION_SAME_DIR";
pub const MIGRATION_FILE_NOT_FOUND: &str = "MIGRATION_FILE_NOT_FOUND";
pub const MIGRATION_FILE_MISMATCH: &str = "MIGRATION_FILE_MISMATCH";

// Claude
pub const CLAUDE_HOME_DIR_ERROR: &str = "CLAUDE_HOME_DIR_ERROR";
pub const CLAUDE_PATH_NOT_IN_SCOPE: &str = "CLAUDE_PATH_NOT_IN_SCOPE";
pub const CLAUDE_INVALID_EXTENSION: &str = "CLAUDE_INVALID_EXTENSION";
pub const CLAUDE_FILE_READ_FAILED: &str = "CLAUDE_FILE_READ_FAILED";

// Journal / Hooks
pub const JOURNAL_INDEX_NOT_FOUND: &str = "JOURNAL_INDEX_NOT_FOUND";
pub const HOOKS_WORKFLOW_NOT_FOUND: &str = "HOOKS_WORKFLOW_NOT_FOUND";

// Notification
pub const NOTIFICATION_UNKNOWN_ERROR: &str = "NOTIFICATION_UNKNOWN_ERROR";
pub const NOTIFICATION_UNSUPPORTED_CHANNEL: &str = "NOTIFICATION_UNSUPPORTED_CHANNEL";

// Sort
pub const SORT_LIST_EMPTY: &str = "SORT_LIST_EMPTY";
pub const SORT_LIST_DUPLICATE: &str = "SORT_LIST_DUPLICATE";

// File
pub const FILE_TRAVERSAL: &str = "FILE_TRAVERSAL";
pub const DIR_ALREADY_EXISTS: &str = "DIR_ALREADY_EXISTS";

// SSH
pub const SSH_HOST_EMPTY: &str = "SSH_HOST_EMPTY";
pub const SSH_REMOTE_PATH_EMPTY: &str = "SSH_REMOTE_PATH_EMPTY";
pub const SSH_REMOTE_PATH_NOT_ABSOLUTE: &str = "SSH_REMOTE_PATH_NOT_ABSOLUTE";
pub const SSH_INVALID_CHARS: &str = "SSH_INVALID_CHARS";
pub const SSH_NOT_FOUND: &str = "SSH_NOT_FOUND";
pub const SSH_IDENTITY_FILE_INVALID: &str = "SSH_IDENTITY_FILE_INVALID";
pub const SSH_PORT_INVALID: &str = "SSH_PORT_INVALID";
pub const SSH_NAME_EMPTY: &str = "SSH_NAME_EMPTY";

// Scan
pub const SCAN_DIR_NOT_FOUND: &str = "SCAN_DIR_NOT_FOUND";

// Generic
pub const UNKNOWN_ERROR: &str = "UNKNOWN_ERROR";
pub const IO_ERROR: &str = "IO_ERROR";
pub const DB_ERROR: &str = "DB_ERROR";
